# Generated by Django 5.2 on 2026-04-07 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashflow_score', models.IntegerField(default=0, help_text='Based on transaction frequency and reliability (weight: 40%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('consistency_score', models.IntegerField(default=0, help_text='Based on regularity of listings and activity (weight: 30%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('collateral_score', models.IntegerField(default=0, help_text='Based on verified transaction volume (weight: 30%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.IntegerField(default=0, help_text='Weighted average of all components', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_sales_volume', models.DecimalField(decimal_places=2, default=0, help_text='Total amount from completed sales', max_digits=15)),
                ('average_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_on_platform', models.IntegerField(default=0)),
                ('active_listings_count', models.IntegerField(default=0)),
                ('completed_trades', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('farmer', models.OneToOneField(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_creditscore',
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, help_text='Amount requested in KES', max_digits=15, validators=[django.core.validators.MinValueValidator(1000)])),
                ('purpose', models.TextField(help_text='Purpose of credit (e.g., farm inputs, equipment, working capital)')),
                ('duration_months', models.IntegerField(default=12, help_text='Repayment period in months', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('credit_score_at_request', models.IntegerField(default=0, help_text='Credit score at time of request')),
                ('recommended_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Recommended credit amount based on score', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Approved credit amount', max_digits=15, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate (%) based on risk assessment', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'creditor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_creditrequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer', 'status'], name='credit_cred_farmer__f446eb_idx'), models.Index(fields=['status'], name='credit_cred_status_fed2a1_idx'), models.Index(fields=['created_at'], name='credit_cred_created_1df097_idx')],
            },
        ),
    ]
