# Generated by Django 4.2.11 on 2026-04-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='supporting_documents',
            field=models.JSONField(blank=True, default=list, help_text='URLs or references to uploaded supporting documents'),
        ),
    ]
