# Generated by Django 4.2.11 on 2026-04-14 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0002_creditrequest_supporting_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(help_text='e.g. Equity Bank, KWFT, SACCO name', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Brief description of the institution and lending products')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='creditor_logos/')),
                ('interest_rate_prime', models.DecimalField(decimal_places=2, default=8.0, help_text='Interest rate for Prime borrowers (%)', max_digits=5)),
                ('interest_rate_low', models.DecimalField(decimal_places=2, default=12.0, help_text='Interest rate for Low Risk borrowers (%)', max_digits=5)),
                ('interest_rate_medium', models.DecimalField(decimal_places=2, default=16.0, help_text='Interest rate for Medium Risk borrowers (%)', max_digits=5)),
                ('interest_rate_high', models.DecimalField(decimal_places=2, default=22.0, help_text='Interest rate for High Risk borrowers (%)', max_digits=5)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, default=5000, help_text='Minimum loan amount in KES', max_digits=12)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, default=1000000, help_text='Maximum loan amount in KES', max_digits=12)),
                ('is_accepting_applications', models.BooleanField(default=True, help_text='If False, this creditor will not appear in the farmer loan form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credit_creditorprofile',
                'ordering': ['institution_name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='creditrequest',
            name='credit_cred_status_fed2a1_idx',
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='collateral_description',
            field=models.TextField(blank=True, default='', help_text='Description of collateral offered (land, equipment, produce etc)'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='collateral_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated collateral value in KES', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='loan_to_cashflow_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='loan amount / avg monthly cashflow (lower = safer)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='risk_classification',
            field=models.CharField(choices=[('prime', 'Prime'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('unclassified', 'Unclassified')], default='unclassified', help_text='Auto-assigned by the credit scoring engine', max_length=15),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='suggested_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate suggested by engine from creditor tier', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='target_creditor',
            field=models.ForeignKey(blank=True, help_text='Creditor this application is directed to', limit_choices_to={'role': 'creditor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_credit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='avg_monthly_cashflow',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average monthly cash inflow (KES)', max_digits=12),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='prime_eligible',
            field=models.BooleanField(default=False, help_text='True when overall_score >= 85'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='approval_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='credit_score_at_request',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final interest rate (%) set by creditor', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='recommended_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='supporting_documents',
            field=models.JSONField(blank=True, default=list, help_text='URLs or paths to uploaded supporting documents'),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='risk_level',
            field=models.CharField(choices=[('prime', 'Prime'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='high', max_length=10),
        ),
        migrations.AddIndex(
            model_name='creditrequest',
            index=models.Index(fields=['target_creditor', 'status'], name='credit_cred_target__e35300_idx'),
        ),
        migrations.AddIndex(
            model_name='creditrequest',
            index=models.Index(fields=['risk_classification'], name='credit_cred_risk_cl_efe82b_idx'),
        ),
        migrations.AddField(
            model_name='creditorprofile',
            name='creditor',
            field=models.OneToOneField(limit_choices_to={'role': 'creditor'}, on_delete=django.db.models.deletion.CASCADE, related_name='creditor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
