# Generated by Django 4.2.11 on 2026-05-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_creditorprofile_and_credit_request_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, default='', max_length=100)),
                ('document_url', models.CharField(max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('credit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='credit.creditrequest')),
            ],
            options={
                'db_table': 'credit_creditdocument',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
