# Generated by Django 4.2.11 on 2026-05-03 13:08

from django.db import migrations

def migrate_supporting_documents(apps, schema_editor):
    CreditRequest = apps.get_model('credit', 'CreditRequest')
    CreditDocument = apps.get_model('credit', 'CreditDocument')

    for req in CreditRequest.objects.all():
        docs = req.supporting_documents or []
        if isinstance(docs, list):
            for url in docs:
                if url:
                    CreditDocument.objects.create(
                        credit_request=req,
                        document_url=url,
                        document_type='Supporting Document',
                        verified=False
                    )
        elif isinstance(docs, dict):
            for k, url in docs.items():
                if url:
                    CreditDocument.objects.create(
                        credit_request=req,
                        document_url=url,
                        document_type=k,
                        verified=False
                    )

class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_creditdocument'),
    ]

    operations = [
        migrations.RunPython(migrate_supporting_documents),
    ]
