# Generated by Django 4.2.11 on 2026-05-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_auto_20260503_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrequest',
            name='supporting_documents',
        ),
    ]
