# Generated by Django 4.2.11 on 2026-05-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_order_amount_paid_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
