# Generated by Django 4.2.11 on 2026-05-03 13:08

from django.db import migrations

def migrate_product_images(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductImage = apps.get_model('products', 'ProductImage')

    for product in Product.objects.all():
        photo_urls = product.photo_urls or []
        for i, url in enumerate(photo_urls):
            if url:
                ProductImage.objects.create(
                    product=product,
                    image_url=url,
                    is_primary=(i == 0)
                )

def migrate_inventory_images(apps, schema_editor):
    InventoryItem = apps.get_model('products', 'InventoryItem')
    InventoryImage = apps.get_model('products', 'InventoryImage')

    for item in InventoryItem.objects.all():
        photo_urls = item.photo_urls or []
        for i, url in enumerate(photo_urls):
            if url:
                InventoryImage.objects.create(
                    inventory_item=item,
                    image_url=url,
                    is_primary=(i == 0)
                )

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_inventoryimage'),
    ]

    operations = [
        migrations.RunPython(migrate_product_images),
        migrations.RunPython(migrate_inventory_images),
    ]
