# Generated by Django 4.2.11 on 2026-05-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20260503_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='photo_urls',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_urls',
        ),
    ]
