# Generated by Django 4.2.11 on 2026-05-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_inventoryitem_photo_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='photo_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
