# Generated by Django 4.2.11 on 2026-05-03 13:53

from django.db import migrations

def migrate_images_to_photo_urls(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductImage = apps.get_model('products', 'ProductImage')
    InventoryItem = apps.get_model('products', 'InventoryItem')
    InventoryImage = apps.get_model('products', 'InventoryImage')

    for product in Product.objects.all():
        images = list(ProductImage.objects.filter(product=product).order_by('-is_primary', 'created_at').values_list('image_url', flat=True))
        if images:
            product.photo_urls = images
            product.save(update_fields=['photo_urls'])

    for item in InventoryItem.objects.all():
        images = list(InventoryImage.objects.filter(inventory_item=item).order_by('-is_primary', 'created_at').values_list('image_url', flat=True))
        if images:
            item.photo_urls = images
            item.save(update_fields=['photo_urls'])

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_inventoryitem_photo_urls_product_photo_urls'),
    ]

    operations = [
        migrations.RunPython(migrate_images_to_photo_urls),
    ]
