# Generated by Django 4.2.11 on 2026-05-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20260503_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='InventoryImage',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
