# Generated by Django 4.2.11 on 2026-05-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productimage_product_delete_inventoryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('checked_out', 'Checked Out')], default='pending', max_length=20),
        ),
    ]
