# Generated by Django 5.2 on 2026-04-07 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_receipt_number', models.CharField(blank=True, default='', help_text='M-Pesa receipt number after successful payment', max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_reference', models.CharField(blank=True, default='SMC', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_mpesatransaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_mp_user_id_196aa4_idx'), models.Index(fields=['checkout_request_id'], name='payments_mp_checkou_a6f836_idx'), models.Index(fields=['mpesa_receipt_number'], name='payments_mp_mpesa_r_3e414a_idx')],
            },
        ),
    ]
