# Generated by Django 5.2 on 2026-04-07 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='', help_text='Detailed feedback on product quality')),
                ('verified_purchase', models.BooleanField(default=True, help_text='Verified that buyer purchased this product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('transaction', models.OneToOneField(help_text='Transaction proof of purchase', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='transactions.transaction')),
            ],
            options={
                'db_table': 'reviews_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'buyer'], name='reviews_rev_product_0cbc00_idx'), models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'), models.Index(fields=['created_at'], name='reviews_rev_created_bdcc91_idx')],
                'unique_together': {('product', 'transaction')},
            },
        ),
    ]
