# Generated by Django 4.2.11 on 2026-04-11 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured role-specific profile data collected from the frontend'),
        ),
        migrations.CreateModel(
            name='StaffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('rate_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_stafflog',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['farmer', 'date'], name='users_staff_farmer__d90b5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_contactinquiry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_conta_email_03e421_idx'), models.Index(fields=['status'], name='users_conta_status_55e08e_idx')],
            },
        ),
    ]
