# Generated by Django 4.2.11 on 2026-04-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_data_stafflog_contactinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=12, null=True),
        ),
    ]
