# Generated by Django 4.2.11 on 2026-04-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fix_latlon_max_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Latitude coordinate', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Longitude coordinate', max_digits=20, null=True),
        ),
    ]
