# Generated by Django 4.2.11 on 2026-05-03 13:07

from django.db import migrations

def migrate_profile_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    FarmerProfile = apps.get_model('users', 'FarmerProfile')
    BuyerProfile = apps.get_model('users', 'BuyerProfile')
    CreditorProfile = apps.get_model('credit', 'CreditorProfile')

    for user in User.objects.all():
        data = user.profile_data or {}
        if not data:
            continue
            
        if user.role == 'farmer':
            FarmerProfile.objects.update_or_create(
                user=user,
                defaults={
                    'farm_size': data.get('farm_size') or None,
                    'farming_type': data.get('farming_type', ''),
                    'certifications': data.get('certifications', ''),
                }
            )
        elif user.role == 'buyer':
            BuyerProfile.objects.update_or_create(
                user=user,
                defaults={
                    'business_name': data.get('business_name', ''),
                    'buyer_type': data.get('buyer_type', ''),
                }
            )
        elif user.role == 'creditor':
            CreditorProfile.objects.update_or_create(
                creditor=user,
                defaults={
                    'institution_name': data.get('institution_name', ''),
                    'interest_rate_prime': data.get('interest_rate_prime', 8.0),
                    'min_loan_amount': data.get('min_loan_amount', 5000),
                    'max_loan_amount': data.get('max_loan_amount', 1000000),
                }
            )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_farmerprofile_buyerprofile'),
        ('credit', '0003_creditorprofile_and_credit_request_v2'),
    ]

    operations = [
        migrations.RunPython(migrate_profile_data),
    ]
