# Generated by Django 4.2.11 on 2026-05-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20260503_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_data',
        ),
    ]
