# Generated by Django 5.2 on 2026-04-07 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=255)),
                ('category', models.CharField(default='general', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit (e.g., per kg)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum market price', max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum market price', max_digits=10, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, help_text='Average market price', max_digits=10, null=True)),
                ('price_trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('source', models.CharField(blank=True, default='', help_text='Data source (e.g., Kenya Agricultural Commodity Exchange)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_marketprice',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['crop_name'], name='market_mark_crop_na_79d204_idx'), models.Index(fields=['category'], name='market_mark_categor_3d6718_idx'), models.Index(fields=['updated_at'], name='market_mark_updated_06ebf4_idx')],
                'unique_together': {('crop_name', 'unit')},
            },
        ),
    ]
