# Generated by Django 4.2.11 on 2026-04-14 19:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketprice',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.RemoveIndex(
            model_name='marketprice',
            name='market_mark_crop_na_79d204_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketprice',
            name='market_mark_updated_06ebf4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='market',
            field=models.CharField(db_index=True, default='Nairobi', max_length=255),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when this price was recorded'),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average market price at time of record', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='category',
            field=models.CharField(db_index=True, default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='crop_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum market price at time of record', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum market price at time of record', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='source',
            field=models.CharField(blank=True, default='', help_text="e.g. 'nextyield', 'kamis_fallback', 'db_cache', 'blended'", max_length=255),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit (e.g., per kg) in KES', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddIndex(
            model_name='marketprice',
            index=models.Index(fields=['crop_name', 'market', '-recorded_at'], name='market_mark_crop_na_85a612_idx'),
        ),
        migrations.AddIndex(
            model_name='marketprice',
            index=models.Index(fields=['recorded_at'], name='market_mark_recorde_180f3c_idx'),
        ),
    ]
