# Generated by Django 5.2 on 2026-04-07 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_crops', models.JSONField(default=list, help_text='List of preferred crop categories')),
                ('search_radius_km', models.IntegerField(default=50, help_text='Search radius for farmer matching')),
                ('min_rating', models.FloatField(default=3.0, help_text='Minimum farmer rating to match')),
                ('notify_on_match', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.OneToOneField(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'geo_buyerpreference',
            },
        ),
        migrations.CreateModel(
            name='BuyerFarmerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('match_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('interaction_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_matches', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'geo_buyerfarmermatch',
                'indexes': [models.Index(fields=['buyer', 'match_score'], name='geo_buyerfa_buyer_i_d276e4_idx'), models.Index(fields=['is_active'], name='geo_buyerfa_is_acti_72acaf_idx')],
                'unique_together': {('buyer', 'farmer')},
            },
        ),
    ]
