# Generated by Django 4.2.11 on 2026-05-03 13:08

from django.db import migrations

def migrate_preferred_crops(apps, schema_editor):
    BuyerPreference = apps.get_model('geo', 'BuyerPreference')
    Crop = apps.get_model('geo', 'Crop')
    BuyerPreferredCrop = apps.get_model('geo', 'BuyerPreferredCrop')

    for pref in BuyerPreference.objects.all():
        crops = pref.preferred_crops or []
        for crop_name in crops:
            if not crop_name:
                continue
            crop, created = Crop.objects.get_or_create(name=crop_name.strip())
            BuyerPreferredCrop.objects.get_or_create(
                buyer=pref.buyer,
                crop=crop
            )

class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_crop_buyerpreferredcrop'),
    ]

    operations = [
        migrations.RunPython(migrate_preferred_crops),
    ]
