# Generated by Django 4.2.11 on 2026-05-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20260503_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerpreference',
            name='preferred_crops',
        ),
    ]
