# Generated by Django 5.2 on 2026-04-07 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales_count', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue from completed transactions', max_digits=15)),
                ('average_sale_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_products_listed', models.IntegerField(default=0)),
                ('active_products', models.IntegerField(default=0)),
                ('sold_out_products', models.IntegerField(default=0)),
                ('total_bids_received', models.IntegerField(default=0)),
                ('bids_accepted', models.IntegerField(default=0)),
                ('acceptance_rate', models.FloatField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.OneToOneField(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_farmeranalytics',
            },
        ),
    ]
